"use client"
import './globals.css'
import { AppProgressBar as ProgressBar } from 'next-nprogress-bar';

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <head>
        <title>Leesangdal Portfolio Website</title>
        <meta name='description' content='Generated by create next app' />
      </head>
      <body>
        {children}
        <ProgressBar
          height="4px"
          color="#fff"
          options={{ showSpinner: true }}
          shallowRouting
        />
      </body>
    </html>
  )
}
