"use client"
import './globals.css'
import { useEffect } from 'react'
import gsap from 'gsap'
import { AppProgressBar as ProgressBar } from 'next-nprogress-bar';

export default function RootLayout({ children }) {
  useEffect(() => {
    let cursor = document.querySelector(".cursorBall");
    const links = document.querySelectorAll("a");

    document.addEventListener("mousemove", (e) => {
      cursor.style.top = e.clientY + "px";
      cursor.style.left = e.clientX + "px";
    });

    const onMouseEnterLink = e => {
      gsap.to(cursor, {scale: 4})
    }

    const onMouseLeaveLink = () => {
      gsap.to(cursor, {scale: 1})
    }

    links.forEach((link) => {
      link.addEventListener("mouseenter", onMouseEnterLink)
      link.addEventListener("mouseleave", onMouseLeaveLink)
    })
  })
  
  return (
    <html lang="ko">
      <head>
        <title>Leesangdal Portfolio Website</title>
        <meta name='description' content='Generated by create next app' />
      </head>
      <body>
        <div className='cursorBall'></div>
        <ProgressBar
          height="4px"
          color="#fff"
          options={{ showSpinner: true }}
          shallowRouting
        />
        {children}
      </body>
    </html>
  )
}
